/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: 9b2ffa3edce2517ccfe9aa6f4d7be055)
// Runtime types generated with workerd@1.20260312.1 2025-04-01
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./workers/app");
  }
  interface Env {
    VALUE_FROM_CLOUDFLARE: "Hello from Hono/CF";
    OPENAI_API_KEY: string;
    SCREENSHOTONE_ACCESS_KEY: string;
  }
}
interface Env extends Cloudflare.Env {}
