/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: 0c51d6dfa5f1bdc5cef004ec4683fb34)
// Runtime types generated with workerd@1.20251217.0 2025-04-01
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./workers/app");
    durableNamespaces: "BackendDurableObject";
  }
  interface Env {
    VALUE_FROM_CLOUDFLARE: "Hello from Hono/CF";
    VITE_CLERK_PUBLISHABLE_KEY: "pk_test_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    CLERK_SECRET_KEY: string;
    BACKEND_DO: DurableObjectNamespace<
      import("./workers/app").BackendDurableObject
    >;
    BUCKET: R2Bucket;
    DB: D1Database;
  }
}
interface Env extends Cloudflare.Env {}
